# Generated by Django 3.1.2 on 2020-11-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_path', models.TextField(verbose_name='Абсолютный путь до папки')),
                ('dir_name', models.TextField(verbose_name='Название папки')),
                ('nodes', models.IntegerField(default=0, verbose_name='Кол-во вершин')),
                ('edges', models.IntegerField(default=0, verbose_name='Кол-во рёбер')),
                ('fulledges', models.IntegerField(default=0, verbose_name='Рёбер в полном графе')),
            ],
            options={
                'verbose_name': 'Информация о графе',
            },
        ),
        migrations.DeleteModel(
            name='GraphInfo',
        ),
        migrations.AddField(
            model_name='imagenode',
            name='real_name',
            field=models.TextField(default='', verbose_name='Название картинки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenode',
            name='image',
            field=models.ImageField(upload_to='upload/node/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='imagenode',
            name='directory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sorter.directorygraph', verbose_name='Папка'),
            preserve_default=False,
        ),
    ]
