# Generated by Django 3.1.2 on 2020-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0002_auto_20201105_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorygraph',
            name='abs_path',
            field=models.TextField(blank=True, verbose_name='Абсолютный путь до папки'),
        ),
    ]
