# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0003_auto_20201105_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorygraph',
            old_name='fulledges',
            new_name='full_edges',
        ),
    ]
