# Generated by Django 3.1.2 on 2020-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0004_auto_20201105_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenode',
            name='image',
            field=models.TextField(default='', verbose_name='Изображение'),
        ),
    ]
