# Generated by Django 3.1.2 on 2020-11-05 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0006_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='method',
            field=models.CharField(default='', max_length=10, verbose_name='Метод'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 1, 49, 43, 887932)),
        ),
    ]
