# Generated by Django 3.1.2 on 2020-11-05 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0007_auto_20201106_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 2, 43, 12, 558971)),
        ),
    ]
