# Generated by Django 3.1.2 on 2020-11-05 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0008_auto_20201106_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 2, 49, 20, 570926)),
        ),
        migrations.AlterField(
            model_name='imagenode',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
