# Generated by Django 3.1.2 on 2020-11-06 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0009_auto_20201106_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 3, 13, 53, 259272)),
        ),
        migrations.AlterField(
            model_name='imagenode',
            name='image',
            field=models.TextField(default='', verbose_name='Изображение'),
        ),
    ]
