# Generated by Django 3.1.2 on 2020-11-06 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0011_auto_20201106_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenode',
            name='xyi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 4, 24, 50, 496958)),
        ),
    ]
