# Generated by Django 3.1.2 on 2020-11-06 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0012_auto_20201106_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenode',
            name='relateto',
        ),
        migrations.RemoveField(
            model_name='imagenode',
            name='xyi',
        ),
        migrations.AddField(
            model_name='imagenode',
            name='relatet',
            field=models.ManyToManyField(related_name='_imagenode_relatet_+', to='sorter.ImageNode', verbose_name='Связан с'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 4, 25, 44, 697975)),
        ),
    ]
